# Generated by Django 3.1.2 on 2023-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone', models.CharField(default='', max_length=15, unique=True)),
                ('otp', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
